name: o lukin e ante

on: pull_request_target

jobs:
  o-lukin-e-ante:
    runs-on: ubuntu-latest
    outputs:
      ante: ${{ steps.dnscontrol_preview.outputs.toki }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # monsuta mute - taso lon la ni li ken ala pakala. toki ilo ale pi
          # lipu ni li anpa ala tawa lipu pi poki ni. jan ike li ante ale e
          # poki ni la ona li lawa e ni taso: ilo DNSControl li lukin e lipu
          # seme pi nimi ilo. lipu li toki ilo JS, taso ilo DNSControl li poki
          # wawa.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: o kama e ilo DNSControl
        uses: gacts/install-dnscontrol@bd76d0934fea4543e839d00d9104c5f6fefc495b # v1.3.1
        with:
          version: v4.34.0

      - name: ilo DNSControl la o lukin e ante
        id: dnscontrol_preview
        env:
          PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
          PORKBUN_SECRET_KEY: ${{ secrets.PORKBUN_SECRET_KEY }}
          KULUPULA_PORKBUN_API_KEY: ${{ secrets.KULUPULA_PORKBUN_API_KEY }}
          KULUPULA_PORKBUN_SECRET_KEY: ${{ secrets.KULUPULA_PORKBUN_SECRET_KEY }}
        run: |
          pini_toki=$(openssl rand -hex 16)
          echo "toki<<$pini_toki" >> "$GITHUB_OUTPUT"
          dnscontrol preview 2>&1 | tee -a "$GITHUB_OUTPUT"
          ponaxp=${PIPESTATUS[0]}
          echo "$pini_toki" >> "$GITHUB_OUTPUT"
          exit $ponaxp

      - name: o toki e ante
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: ${{ !cancelled() }}
        env:
          TOKI: ${{ steps.dnscontrol_preview.outputs.toki }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.TOKI,
            });
